$(document.getElementById("przycisk")).click(function(){
    $(document.getElementById("tresc")).slideToggle(300);
}); 
$(document.getElementById("przyciskk")).click(function(){
    $(document.getElementById("trescc")).slideToggle(300);
});
$(document.getElementById("przyciskkk")).click(function(){
    $(document.getElementById("tresccc")).slideToggle(300);
});
